[package]
name = "rust-sdf"
version = "0.1.0"
authors = ["Nico van Bentum"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.17.1"
rayon = "1.5"
image = "0.23.14"